### PR TITLE
Replace BigDecimal.new with BigDecimal()

### PR DESCRIPTION
**Pull request by paulfri**
Deprecated in mri 2.5.0

### CODE REVIEW

**Comment by ramontayag** [comment]
Thanks!

**Comment by djones** [comment]
It appears this change didn't make it into v1.2.0 https://github.com/bloom-solutions/dry-validation-matchers/blob/v1.2.0/lib/dry/validation/matchers/validate_matcher.rb#L19

Our app repeats this line quite often and I'd love to be able to silence it.

```
/app/.bundle/gems/dry-validation-matchers-1.2.0/lib/dry/validation/matchers/validate_matcher.rb:19: warning: BigDecimal.new is deprecated; use BigDecimal() method instead.
```

@ramontayag would you mind cutting a new version with this fix included?

**Comment by ramontayag** [comment]
Ok just released :+1:

**Comment by djones** [comment]
Awesome, thank you!

**Pull request merged**
